name: BlockHeads APP Production CI 

on:
  push:
    branches:
      - "main"

env:
  AWS_REGION: ap-southeast-1
  CI: false

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    environment: production
    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Cache node_modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.os }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-

      - name: Install packages
        run: npm install

      - name: Build
        run: npm run build

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ env.AWS_REGION }}
      
      - name: Copy files to build files with the AWS CLI
        run: |
          aws s3 sync build s3://blockheads.metasekai.xyz --delete --cache-control max-age=604800,public
          aws s3 cp s3://blockheads.metasekai.xyz/index.html s3://blockheads.metasekai.xyz/index.html --metadata-directive REPLACE --cache-control max-age=0,no-cache,no-store,must-revalidate --content-type text/html --acl public-read

      - name: Invalidate Cloudfont
        run: |
          aws cloudfront create-invalidation --distribution-id E2DN8U8X3OYUG8 --paths "/*"
          
      - name: Discord notification
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        uses: Ilshidur/action-discord@master
        with:
          args: 'The app for {{ EVENT_PAYLOAD.repository.full_name }} has been deployed to https://blockheads.metasekai.xyz'

